/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BubbleInfo: typeof import('./components/bubble/BubbleInfo.vue')['default']
    CenterMapButton: typeof import('./components/fab/CenterMapButton.vue')['default']
    ChangeMapTypeButton: typeof import('./components/fab/ChangeMapTypeButton.vue')['default']
    Counter: typeof import('./components/menu/Counter.vue')['default']
    CounterButton: typeof import('./components/fab/CounterButton.vue')['default']
    Dialog: typeof import('./components/fab/settings/Dialog.vue')['default']
    Drawer: typeof import('./components/menu/Drawer.vue')['default']
    EventBubble: typeof import('./components/bubble/EventBubble.vue')['default']
    EventInfoSheet: typeof import('./components/EventInfoSheet.vue')['default']
    ExempleFile: typeof import('./components/information/ExempleFile.vue')['default']
    FabButton: typeof import('./components/FabButton.vue')['default']
    FileTooLargeDialog: typeof import('./components/FileTooLargeDialog.vue')['default']
    GitHubButton: typeof import('./components/information/GitHubButton.vue')['default']
    GradientBubble: typeof import('./components/bubble/GradientBubble.vue')['default']
    InfoButton: typeof import('./components/fab/InfoButton.vue')['default']
    InformationContent: typeof import('./components/information-components/InformationContent.vue')['default']
    InformationDrawer: typeof import('./components/information/InformationDrawer.vue')['default']
    LoadingCard: typeof import('./components/state/LoadingCard.vue')['default']
    Minimap: typeof import('./components/map/Minimap.vue')['default']
    MulticolorBubble: typeof import('./components/bubble/MulticolorBubble.vue')['default']
    PauseCard: typeof import('./components/state/PauseCard.vue')['default']
    Player: typeof import('./components/menu/Player.vue')['default']
    PlayingCard: typeof import('./components/state/PlayingCard.vue')['default']
    Portals: typeof import('./components/menu/Portals.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RareCaseBubble: typeof import('./components/bubble/RareCaseBubble.vue')['default']
    RegularBubble: typeof import('./components/bubble/RegularBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/fab/SettingsButton.vue')['default']
    SettingsDialog: typeof import('./components/fab/SettingsDialog.vue.vue')['default']
    SettingsMap: typeof import('./components/SettingsMap.vue')['default']
    StateCard: typeof import('./components/StateCard.vue')['default']
    StoppedCard: typeof import('./components/state/StoppedCard.vue')['default']
    Timer: typeof import('./components/menu/Timer.vue')['default']
    TranslationButton: typeof import('./components/fab/TranslationButton.vue')['default']
    VersionCard: typeof import('./components/drawer-modules/VersionCard.vue')['default']
    WorldMap: typeof import('./components/map/WorldMap.vue')['default']
  }
}
