/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Appbar.vue')['default']
    CenterMapButton: typeof import('./components/appbar-buttons/CenterMapButton.vue')['default']
    ChangeMapTypeButton: typeof import('./components/appbar-buttons/ChangeMapTypeButton.vue')['default']
    Counter: typeof import('./components/drawer-modules/Counter.vue')['default']
    Description: typeof import('./components/drawer-modules/Description.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    FileTooLargeDialog: typeof import('./components/FileTooLargeDialog.vue')['default']
    InfoButton: typeof import('./components/appbar-buttons/InfoButton.vue')['default']
    InformationContent: typeof import('./components/information-components/InformationContent.vue')['default']
    InformationDrawer: typeof import('./components/information-components/InformationDrawer.vue')['default']
    LoadingCard: typeof import('./components/state-cards/LoadingCard.vue')['default']
    Minimap: typeof import('./components/Minimap.vue')['default']
    PauseCard: typeof import('./components/state-cards/PauseCard.vue')['default']
    Player: typeof import('./components/drawer-modules/Player.vue')['default']
    PlayingCard: typeof import('./components/state-cards/PlayingCard.vue')['default']
    Portals: typeof import('./components/drawer-modules/Portals.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/appbar-buttons/SettingsButton.vue')['default']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
    StateCard: typeof import('./components/StateCard.vue')['default']
    StoppedCard: typeof import('./components/state-cards/StoppedCard.vue')['default']
    Timer: typeof import('./components/drawer-modules/Timer.vue')['default']
    TranslationButton: typeof import('./components/appbar-buttons/TranslationButton.vue')['default']
    VersionCard: typeof import('./components/VersionCard.vue')['default']
    WorldMap: typeof import('./components/WorldMap.vue')['default']
  }
}
