/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Appbar.vue')['default']
    BubbleInfo: typeof import('./components/event-bubble-components/BubbleInfo.vue')['default']
    CenterMapButton: typeof import('./components/fab-menu/CenterMapButton.vue')['default']
    ChangeMapTypeButton: typeof import('./components/fab-menu/ChangeMapTypeButton.vue')['default']
    Counter: typeof import('./components/drawer-modules/Counter.vue')['default']
    CounterButton: typeof import('./components/fab-menu/CounterButton.vue')['default']
    Description: typeof import('./components/drawer-modules/Description.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    EventBubble: typeof import('./components/event-bubble-components/EventBubble.vue')['default']
    FabButton: typeof import('./components/FabButton.vue')['default']
    FileTooLargeDialog: typeof import('./components/FileTooLargeDialog.vue')['default']
    GradientBubble: typeof import('./components/event-bubble-components/GradientBubble.vue')['default']
    InfoButton: typeof import('./components/fab-menu/InfoButton.vue')['default']
    InformationContent: typeof import('./components/information-components/InformationContent.vue')['default']
    InformationDrawer: typeof import('./components/information-components/InformationDrawer.vue')['default']
    LoadingCard: typeof import('./components/state-cards/LoadingCard.vue')['default']
    Minimap: typeof import('./components/Minimap.vue')['default']
    MulticolorBubble: typeof import('./components/event-bubble-components/MulticolorBubble.vue')['default']
    PauseCard: typeof import('./components/state-cards/PauseCard.vue')['default']
    Player: typeof import('./components/drawer-modules/Player.vue')['default']
    PlayingCard: typeof import('./components/state-cards/PlayingCard.vue')['default']
    Portals: typeof import('./components/drawer-modules/Portals.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RegularBubble: typeof import('./components/event-bubble-components/RegularBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/fab-menu/SettingsButton.vue')['default']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
    StateCard: typeof import('./components/StateCard.vue')['default']
    StoppedCard: typeof import('./components/state-cards/StoppedCard.vue')['default']
    Timer: typeof import('./components/drawer-modules/Timer.vue')['default']
    TranslationButton: typeof import('./components/fab-menu/TranslationButton.vue')['default']
    VersionCard: typeof import('./components/VersionCard.vue')['default']
    WorldMap: typeof import('./components/WorldMap.vue')['default']
  }
}
