version: "3.3"

services:
  viewer:
    build:
      context: ./services/viewer
    container_name: bibliomap-viewer-prod
    environment:
      ENRICHER_WEBSOCKET_URL: http://localhost:59780
    command: "npm start"
    ports:
      - 3000:3000
    restart: unless-stopped

  player:
    build:
      context: ./services/player
    container_name: bibliomap-player-prod
    command: "npm start"
    ports:
      - 3001:3000
    restart: unless-stopped

  enricher:
    build:
      context: ./services/enricher
    container_name: bibliomap-enricher-prod
    command: "npm start"
    restart: unless-stopped

  ezpaarse:
    container_name: bibliomap-ezpaarse-prod
    image: ezpaarseproject/ezpaarse:3.12.0
    environment:
      NODE_ENV: "production"
      EZPAARSE_MONGO_URL: "mongodb://ezpaarse_db:27017/ezpaarse"
    volumes:
      - ./data/ezpaarse/platforms:/opt/ezpaarse/platforms
      - ./data/ezpaarse/middlewares:/opt/ezpaarse/middlewares
      - ./data/ezpaarse/resources:/opt/ezpaarse/resources
      - ./data/ezpaarse/exclusions:/opt/ezpaarse/exclusions
    ports:
      - 59599:59599
    depends_on:
      - ezpaarse_db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:59599 || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  ezpaarse_db:
    container_name: bibliomap-ezpaarse-db-prod
    image: mongo:7.0.20

  bibliomap_nginx:
    build:
      context: ./services/nginx
    container_name: bibliomap_nginx
    ports:
      - 80:80
    environment:
      - NGINX_HOST=localhost
      - PLAYER_URL=http://bibliomap_player:3000/
      - VIEWER_URL=http://bibliomap_viewer:3000/
      - ENRICHER_WEBSOCKET_URL=bibliomap_enricher:27780
    restart: unless-stopped
    depends_on:
      player:
        condition: service_healthy
      viewer:
        condition: service_healthy
