version: "3.3"

services:

  viewer:
    image: node:22.14.0
    container_name: bibliomap-viewer-dev
    environment:
      NODE_ENV: "development"
      BBV_INDEX: cnrs
      BBV_JSFILE: bibliomap-cnrs.js
      BBV_LISTEN_ENRICHER_HOST: "0.0.0.0"
      BBV_LISTEN_ENRICHER_PORT: 27779
      VITE_ENRICHER_WEBSOCKET_URL: localhost:27780
    command: "npm run dev"
    working_dir: /usr/src/app
    volumes: 
      - ./services/viewer:/usr/src/app
    ports:
      - 50197:50197
    restart: unless-stopped
    depends_on:
      enricher:
        condition: service_healthy

  enricher:
    image: node:22.14.0
    container_name: bibliomap-enricher-dev
    environment:
      NODE_APP_INSTANCE: ${NODE_APP_INSTANCE}
      BBE_EZPAARSE_URL: "http://ezpaarse:59599"
      BBE_LISTEN_HARVESTER_HOST: "0.0.0.0"
      BBE_LISTEN_HARVESTER_PORT: 27777
      BBE_BROADCAST_VIEWER_HOST: "viewer"
      BBE_BROADCAST_VIEWER_PORT: 27779
      WEBSOCKET_PORT: 27780
      BBE_EZPAARSE_PREDEF: bibliomap
      REPLAY_FILE_PATHS: ${REPLAY_FILE_PATHS}
      REPLAY_START_DAY: ${REPLAY_START_DAY}
      REPLAY_START_TIME: ${REPLAY_START_TIME}
      REPLAY_MULTIPLIER: ${REPLAY_MULTIPLIER}
      REPLAY_MODE: ${REPLAY_MODE}
      DURATION: ${REPLAY_DURATION}
    command: "npm run dev"
    working_dir: /usr/src/app
    volumes: 
      - ./services/enricher:/usr/src/app
    restart: unless-stopped
    depends_on:
      ezpaarse:
        condition: service_healthy
    ports:
      - 27780:27780
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:27780 || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  ezpaarse:
    container_name: bibliomap-ezpaarse-dev
    image: ezpaarseproject/ezpaarse:3.4.0
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "production"
      EZPAARSE_MONGO_URL: "mongodb://ezpaarse_db:27017/ezpaarse"
    ports:
      - 59599:59599
    depends_on:
      - ezpaarse_db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:59599 || exit 1"
        ]
      interval: 15s
      timeout: 15s
      retries: 10
    #restart: unless-stopped

  ezpaarse_db:
    container_name: bibliomap-ezpaarse-db-dev
    image: mongo:3.4.1
    command: --smallfiles
    #restart: unless-stopped
