version: "3.3"

services:

  viewer:
    extra_hosts:
      - host.docker.internal:host-gateway
    build: 
      context: ./services/viewer
    container_name: bibliomap-viewer-dev
    environment:
      NODE_ENV: "development"
      BBV_INDEX: cnrs
      BBV_JSFILE: bibliomap-cnrs.js
      BBV_LISTEN_ENRICHER_HOST: "0.0.0.0"
      BBV_LISTEN_ENRICHER_PORT: 27779
      BBV_LISTEN_HOST: "0.0.0.0"
      BBV_LISTEN_PORT: 50198 # web server
    develop:
      watch:
        - action: sync+restart
          path: ./services/viewer
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/viewer/package.json
    command: "npm start"
    ports:
      - 50198:50198
      - 27779:27779
    restart: unless-stopped

  enricher:
    build:
      context: ./services/enricher
    container_name: bibliomap-enricher-dev
    environment:
      NODE_APP_INSTANCE: ${NODE_APP_INSTANCE}
      BBE_EZPAARSE_URL: "http://ezpaarse:59599"
      BBE_LISTEN_HARVESTER_HOST: "0.0.0.0"
      BBE_LISTEN_HARVESTER_PORT: 27777
      BBE_BROADCAST_VIEWER_HOST: "viewer"
      BBE_BROADCAST_VIEWER_PORT: 27779
      BBE_EZPAARSE_PREDEF: bibliomap
    develop:
      watch:
        - action: sync+restart
          path: ./services/enricher
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/enricher/package.json
    command: "npm start"
    restart: unless-stopped

  harvester:
    build: 
      context: ./services/harvester
    container_name: bibliomap-harvester-dev
    environment:
      BBH_ENRICHER_HOST: "enricher"
      BBH_ENRICHER_PORT: 27777
      BBH_NO_DEMO:     "" # demo is activated
      BBH_STREAMNAMES: "" # default streams are for the demo
      BBH_STREAMPATHS: ""
      BBH_LOG_FOLDER: demo-logs/cnrs
      NODE_APP_INSTANCE: cnrs
      BBH_LOGS_PER_SECOND: 1
    develop:
      watch:
        - action: sync+restart
          path: ./services/harvester
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/harvester/package.json
    volumes:
      - ./services/harvester/demo-logs/:/app/demo-logs
    command: "npm run dev"
    restart: unless-stopped

  ezpaarse:
    container_name: bibliomap-ezpaarse-dev
    image: ezpaarseproject/ezpaarse:3.4.0
    links:
      - ezpaarse_db
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "production"
      EZPAARSE_MONGO_URL: "mongodb://ezpaarse_db:27017/ezpaarse"
    ports:
      - 59599:59599
    depends_on:
      - ezpaarse_db
    #restart: unless-stopped

  ezpaarse_db:
    container_name: bibliomap-ezpaarse-db-dev
    image: mongo:3.4.1
    command: --smallfiles
    #restart: unless-stopped
