version: "3.3"

services:
  viewer:
    image: node:22.14.0
    container_name: bibliomap-viewer-dev
    environment:
      ENRICHER_WEBSOCKET_URL: http://localhost:59780
    command: "npm run dev"
    working_dir: /usr/src/app
    volumes: 
      - ./services/viewer:/usr/src/app
    ports:
      - 3000:3000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"
        ]
      interval: 2s
      timeout: 2s
      retries: 10

  enricher:
    image: node:22.14.0
    container_name: bibliomap-enricher-dev
    command: "npm run dev"
    working_dir: /usr/src/app
    volumes: 
      - ./services/enricher:/usr/src/app
    restart: unless-stopped
    ports:
      - 59780:59780

  player:
    image: node:22.14.0
    container_name: bibliomap-player-dev
    command: "npm run dev"
    working_dir: /usr/src/app
    volumes:
      - ./services/player:/usr/src/app
    ports:
      - 3001:3000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"
        ]
      interval: 2s
      timeout: 2s
      retries: 10

  redis:
    image: redis:8.10.0-alpine3.23
    container_name:  bibliomap-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD-changeme}
      --appendonly yes

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.19.20
    container_name: bibliomap-filebeat-dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD-changeme}
      REDIS_KEY: ezproxy-logs
    restart: unless-stopped
    volumes:
      - ./services/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      # Adapte ce chemin vers le dossier réel contenant tes 10 fichiers de logs
      - ./services/filebeat/log:/var/log/ezproxy:ro
    command: ["--strict.perms=false"]

  ezpaarse:
    container_name: bibliomap-ezpaarse-dev
    image: ezpaarseproject/ezpaarse:3.12.0
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "production"
      EZPAARSE_MONGO_URL: "mongodb://ezpaarse_db:27017/ezpaarse"
    volumes:
      - ./data/ezpaarse/platforms:/opt/ezpaarse/platforms
      - ./data/ezpaarse/middlewares:/opt/ezpaarse/middlewares
      - ./data/ezpaarse/resources:/opt/ezpaarse/resources
      - ./data/ezpaarse/exclusions:/opt/ezpaarse/exclusions
    ports:
      - 59599:59599
    depends_on:
      - ezpaarse_db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -Y off --no-verbose --tries=1 --spider http://localhost:59599 || exit 1"
        ]
      interval: 2s
      timeout: 2s
      retries: 10
    #restart: unless-stopped

  ezpaarse_db:
    image: mongo:7.0.20
    container_name: bibliomap-ezpaarse-db-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 2s
      timeout: 2s
      retries: 10

  nginx:
    image: nginx:1.29.1
    container_name: bibliomap-nginx-dev
    environment:
      # host of service
      - VIEWER_URL=http://viewer:3000
      - PLAYER_URL=http://player:3000
      - ENRICHER_WEBOCKET_URL=http://bibliomap_enricher:27780
    ports:
      - 80:80
    volumes:
      - ./services/nginx/templates/http.conf.template:/etc/nginx/templates/default.conf.template:ro
    restart: unless-stopped
    depends_on:
      viewer:
        condition: service_healthy
      player:
        condition: service_healthy
    healthcheck:
      test: [
        "CMD-SHELL",
        "service nginx status || exit 1" 
      ]
      interval: 10s
      timeout: 10s
      retries: 5