version: '2'

services:

  bibliomap-viewer:
    container_name: bibliomap-viewer
    image: ezpaarseproject/bibliomap-viewer:Mise à jour 0d74947..0c113e0 Fast-forward README.md | 2 +- bibliomap-cnrs.js | 48 +++++++++++++++++++++++++++++++++--------------- index-cnrs.html | 14 +++++++++----- public/css/style.css | 8 ++++++++ 4 files changed, 51 insertions(+), 21 deletions(-) 3.0.6
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "production"
      DEBUG: ${DEBUG}
      BBV_INDEX: "index-cnrs.html"
      BBV_JSFILE: "bibliomap-cnrs.js"
      BBV_LISTEN_ENRICHER_HOST: "0.0.0.0"
      BBV_LISTEN_ENRICHER_PORT: 27779
      BBV_LISTEN_HOST: "0.0.0.0"
      BBV_LISTEN_PORT: 50197 # web server
    working_dir: /app
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    ports:
      - 50197:50197
      - 27779:27779
    #restart: unless-stopped

  bibliomap-enricher:
    container_name: bibliomap-enricher
    image: ezpaarseproject/bibliomap-enricher:Already up-to-date. 3.1.4
    links:
      - bibliomap-viewer
      - ezpaarse
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "production"
      DEBUG: ${DEBUG}
      BBE_EZPAARSE_URL: "http://ezpaarse:59599"
      BBE_EZPAARSE_PREDEF: "00-fr-bibcnrs"
      BBE_LISTEN_HARVESTER_HOST: "0.0.0.0"
      BBE_LISTEN_HARVESTER_PORT: 27777
      BBE_BROADCAST_VIEWER_HOST: "bibliomap-viewer"
      BBE_BROADCAST_VIEWER_PORT: 27779
    working_dir: /app
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    #restart: unless-stopped

  bibliomap-harvester:
    container_name: bibliomap-harvester
    image: ezpaarseproject/bibliomap-harvester:Already up-to-date. 2.1.5
    links:
      - bibliomap-enricher
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "production"
      DEBUG: ${DEBUG}
      BBH_ENRICHER_HOST: "bibliomap-enricher"
      BBH_ENRICHER_PORT: 27777
      BBH_NO_DEMO:     "" # demo is activated
      BBH_STREAMNAMES: "" # default streams are for the demo
      BBH_STREAMPATHS: ""
    working_dir: /app
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    #restart: unless-stopped

  ezpaarse:
    container_name: ezpaarse
    image: ezpaarseproject/ezpaarse:Mise à jour 3277529..f796d69 Fast-forward doc/features/geolocalisation.md | 16 +++++++------- lib/hostlocalize.js | 2 -- lib/pkbvalidator.js | 49 ++++++++++++++++++++++------------------- 3 files changed, 34 insertions(+), 33 deletions(-) 2.9.6
    links:
      - ezpaarse_db
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "production"
      EZPAARSE_MONGO_URL: "mongodb://ezpaarse_db:27017/ezpaarse"
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the container
    ports:
      - 59599:59599
    depends_on:
      - ezpaarse_db
    #restart: unless-stopped

  ezpaarse_db:
    container_name: ezpaarse_db
    image: mongo:3.4.1
    command: --smallfiles
    #restart: unless-stopped
