/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InfoMap: typeof import('./components/WorldMap.vue')['default']
    LeftDrawer: typeof import('./components/LeftDrawer.vue')['default']
    LogBubble: typeof import('./components/LogBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WorldMap: typeof import('./components/WorldMap.vue')['default']
  }
}
