/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CenterMapButton: typeof import('./components/fab-menu/CenterMapButton.vue')['default']
    ChangeMapTypeButton: typeof import('./components/fab-menu/ChangeMapTypeButton.vue')['default']
    Counter: typeof import('./components/drawer-modules/Counter.vue')['default']
    CounterButton: typeof import('./components/fab-menu/CounterButton.vue')['default']
    CounterDrawer: typeof import('./components/CounterDrawer.vue')['default']
    Description: typeof import('./components/drawer-modules/Description.vue')['default']
    DialogContent: typeof import('./components/DialogContent.vue')['default']
    DialogDrawer: typeof im./components/CounterDrawer.vueogDrawer.vue')['default']
    Drawer: typeof import('./components/Drawer.vue')['default']
    FabButton: typeof import('./components/FabButton.vue')['default']
    InfoButton: typeof import('./components/fab-menu/InfoButton.vue')['default']
    InformationContent: typeof import('./components/information-components/InformationContent.vue')['default']
    InformationDrawer: typeof import('./components/information-components/InformationDrawer.vue')['default']
    LiveCard: typeof import('./components/mode-cards/LiveCard.vue')['default']
    LiveTimer: typeof import('./components/drawer-modules/timers-components/LiveTimer.vue')['default']
    LogBubble: typeof import('./components/LogBubble.vue')['default']
    Minimap: typeof import('./components/Minimap.vue')['default']
    ModeCard: typeof import('./components/ModeCard.vue')['default']
    ModeIndicator: typeof import('./components/ModeIndicator.vue')['default']
    ParametersDialog: typeof import('./components/ParametersDialog.vue')['default']
    Portals: typeof import('./components/drawer-modules/Portals.vue')['default']
    ReplayCard: typeof import('./components/mode-cards/ReplayCard.vue')['default']
    ReplayDescription: typeof import('./components/drawer-modules/ReplayDescription.vue')['default']
    ReplayTimer: typeof import('./components/drawer-modules/timers-components/ReplayTimer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsButton: typeof import('./components/fab-menu/SettingsButton.vue')['default']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
    Timer: typeof import('./components/drawer-modules/Timer.vue')['default']
    TranslationButton: typeof import('./components/fab-menu/TranslationButton.vue')['default']
    VersionCard: typeof import('./components/VersionCard.vue')['default']
    WorldMap: typeof import('./components/WorldMap.vue')['default']
  }
}
